### PR TITLE
Fixing tenant project show, closes #155

### LINKED ISSUE #155: chore: I AM WORKING ON TENANT PROJECT SHOW PAGE

### PR DESCRIPTION
**Pull request by Jwan622**
-fixed tenant project page
-fixed tenant show page
-added a test
-removed precompiled assets

### CODE REVIEW

**Comment by mikedao** [comment]
Fixing this should be a priority.

screen shot 2015-02-20 at 12 12 24 pm

**Comment by EmilyMB** [comment]
@mikedao I think it is fine. He just deleted all those files.

**Comment by mikedao** [comment]
No auto merge, I think master needs to be merged in.

**Comment by mikedao** [comment]
Thumbs up.

:+1:

**Pull request merged**
