### PR TITLE
Multitenancy 4 lyfe

### PR DESCRIPTION
**Pull request by mikedao**
This branch was created to set up the basic skeleton for multi-tenancy. We worked through these changes as a group. Due to the drastic shift from a coffee shop to a multi-tenant app, significant functionality has been broken.

Changes include:
* Rework existing data tables
* Add Admin and Tenant Models
* Add scope in routes file to account for multi-tenancy

### CODE REVIEW

**Comment by mikedao** [comment]
Ignored the hound changes for user test and guest_user_test because we are drastically changing those anyhow.

**Comment by oorion** [comment]
There are a few more hound changes that we should probably fix.  I also think it might be a good idea to remove the old guest_user_test that was commented out.  What are your thoughts?

**Comment by mikedao** [comment]
Hound is now completely clean.

**Comment by EmilyMB** [comment]
As a group, we agreed to merge despite the broken functionality in order to have a baseline to work from.

**Pull request merged**
